version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    target-branch: upgrade
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    target-branch: upgrade
    schedule:
      interval: daily